### ISSUE TITLE
Installation doesn't work: 

### ISSUE THREAD

**Issue by emilio-cartoni** [AIcrowd/real_robots#1]
* real-robots version:
* Python version:
* Operating System:

### Description
After installation, importing real_robots fails.

### What I Did
> pip3 install --user -U real_robots
> ipython
> In [1]: import real_robots                                                      
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-5617f93867b2> in <module>
> ----> 1 import real_robots
> 
> ~/.local/lib/python3.5/site-packages/real_robots/__init__.py in <module>
>      18 )
>      19 
> ---> 20 from real_robots.envs import env as real_robot_env
>      21 from real_robots.evaluate import evaluate
>      22 
> 
> ImportError: No module named 'real_robots.envs'

This does not happen if I launch ipython while standing in the real_robots directory (that I git cloned), since it can successfully resolve the real_robots.envs path.
However, since the package is installed via PiPy it shouldn't be a requirement to have a copy downloaded and also to stand in there while importing the package.

**Comment by spMohanty** [comment]
@emilio-cartoni : Good catch !! I pushed a fix for this. It was a mistake at my end in how some files were being referenced.
Can you try again by doing : 
```
pip3 install --user -U real_robots
```
This should install `v0.1.4` (or more 👼 ).

**Comment by emilio-cartoni** [comment]
> @emilio-cartoni : Good catch !! I pushed a fix for this. It was a mistake at my end in how some files were being referenced.
> Can you try again by doing :
> 
> ```
> pip3 install --user -U real_robots
> ```
> 
> This should install `v0.1.4` (or more angel ).

It works! Tried both examples, local usage and evaluation :)

**Comment by emilio-cartoni** [comment]
It happened again:
ImportError: No module named 'real_robots.envs'

Regression?

**Comment by spMohanty** [comment]
@emilio-cartoni : Weird, we tested it in a few setups, and seemed to work. Can you try re-installing it in a fresh env, and see if it works ?
Else, I have a not-so-beautiful way of dealing with it, when the library manipulates the python path to ensure the lib python path is definitely setup in the correct way.

**Comment by emilio-cartoni** [comment]
Tested on a laptop and it worked.
Will try again on the office desktop tomorrow... maybe reinstalling multiple times (sometimes with pip, sometimes as a local installation) messed up something.

**Comment by spMohanty** [comment]
Okay, I will have this open for sometime and see if others face the same issue.

**Comment by emilio-cartoni** [comment]
Reinstalled on the office desktop (pip, 0.1.6) and it worked.
