### ISSUE TITLE
Environment assumes goals.npy.npz but no such file is provided.

### ISSUE THREAD

**Issue by emilio-cartoni** [AIcrowd/real_robots#15]
In the `REALRobotEnv` class, we assume in the `__init__` that the `goals_dataset_path` will be `goals_dataset.npy.npz `.
However, if the user does:
```
import gym, real_robots
env = gym.make('REALRobot-v0')
env.set_goal()
```
This will fail as no such `goals_dataset.npy.npz ` is provided.
Indeed, in the README we say that users can download such file from https://aicrowd-production.s3.eu-central-1.amazonaws.com/misc/REAL-Robots/goals.npy.npz

~~On the other hand, we do have the file on the repository (since we also use it to ensure everything works).~~ 

Is this the behavior we want?
Or do we want to:
1) change the environment so that it loads some file from the package (not sure how..)
2) change the environment so that it does not load anything.... However, it would not be able to go to the extrinsic phase so this is more or less pointless..
3) Keep the way it is, and maybe add something to the FAQ

I answer myself and I guess 3 is good :)

**Comment by spMohanty** [comment]
@emilio-cartoni : Yeah, I considered packaging the dataset file in the package itself. But it bloats up the package quite a bit (by 30MB), without adding much added advantage. The best we can do is maybe add a function which downloads the file from the above mentioned link, if it cannot find the link (after ofcourse giving a due warning !).

**Comment by emilio-cartoni** [comment]
I have updated the FAQ to mention the FileNotFound issue and also that they can generate their own files.
Auto-download would be cool but since we have other issues to solve I wouldn't spend time on it, I think it's fine enough the way it is.
I think we can close this :)
