### ISSUE TITLE
Detailed scores for goals

### ISSUE THREAD

**Issue by emilio-cartoni** [AIcrowd/real_robots#17]
In the current evaluation function, there is no way for the user to know which goals succeeded and which goals failed.
The individual score for a single goal is neither displayed nor returned.
Can the `evaluation` function return the `scores` variable as well (maybe renamed as `detailed_scores`) or would it break something?
(I am thinking about people testing locally, not suggesting to display this detailed score online).

**Comment by spMohanty** [comment]
Can you push a fix which demonstrates the capturing of the status of each of the goals ? 

We will not be rendering it on the realtime evaluation feedback as it would be too much information, but we can very well show that on local evaluation.

**Comment by emilio-cartoni** [comment]
Done, and updated README.md.
If it's okay for you we can close this :)
