### ISSUE TITLE
range value of 1 node

### ISSUE THREAD

**Issue by vitiennam** [AIcrowd/real_robots#21]
Hi,

Could you tell me the range value of 1 element in observation["joint_positions"] ???

Thanks

**Comment by emilio-cartoni** [comment]
Dear @kimchicanh ,
the range values for the elements of observation["joint_positions"] should be the same as the range for the action: i.e. between -pi/2 and +pi/2 for the first 7 joints and between 0 and +pi/2 for the gripper joints.
For more details, see https://github.com/AIcrowd/real_robots/blob/master/environment.md and also this recent discussion thread: https://discourse.aicrowd.com/t/strange-realrobot-v0-environment-properties/1857/3 

Edit: I have observed that sometimes the joints may exceed their range when the arm is in contact with other objects (i.e. pushing against the table).
