### ISSUE TITLE
Goal miss match in extrinsic phase

### ISSUE THREAD

**Issue by tkyaaida** [AIcrowd/real_robots#23]
I noticed that the first `obs['goal']` the controller receives in each extrinsic trial is actually one before. I think this is due to setting a goal after creating observation by resetting environment.

I think simple fix would be something like below: 
```
    def run_extrinsic_trial(self, trial_number):
        observation = self.env.reset()
        reward = 0
        done = False
        self.env.set_goal()

        observation['goal'] = self.env.goal.retina
```

https://github.com/AIcrowd/real_robots/blob/3f6cb2db467d0a7c251de1edc2828a3bb82f81dc/real_robots/evaluate.py#L240-L244

**Comment by spMohanty** [comment]
@tkyaaida : Thanks for pointing it out. Can you please send across a pull request with the described change ?
