### ISSUE TITLE
AttributeError: 'BodyPart' object has no attribute 'get_position'

### ISSUE THREAD

**Issue by ckeown** [AIcrowd/real_robots#25]
### What I Did
I tried running real-robots-demo at the terminal, as well as the python code in the readme, but I seem to get the same error. See below. I tested it directly, and the important seems to execute fine. Any thoughts? Thanks!

### Output
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Users/christopherkeown$ real-robots-demo
pybullet build time: Jul 15 2018 17:08:59

#####################################################################################################################
#####################################################################################################################
.______       _______     ___       __         .______        ______   .______     ______   .___________.    _______.
|   _  \     |   ____|   /   \     |  |        |   _  \      /  __  \  |   _  \   /  __  \  |           |   /       |
|  |_)  |    |  |__     /  ^  \    |  |        |  |_)  |    |  |  |  | |  |_)  | |  |  |  | `---|  |----`  |   (----`
|      /     |   __|   /  /_\  \   |  |        |      /     |  |  |  | |   _  <  |  |  |  |     |  |        \   \    
|  |\  \----.|  |____ /  _____  \  |  `----.   |  |\  \----.|  `--'  | |  |_)  | |  `--'  |     |  |    .----)   |   
| _| `._____||_______/__/     \__\ |_______|   | _| `._____| \______/  |______/   \______/      |__|    |_______/    
#####################################################################################################################
#####################################################################################################################
        
1) Testing setup without visualisation : 
/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/pybullet_envs/data/kuka_gripper_description/urdf/kuka_gripper.urdf
Traceback (most recent call last):
  File "/Users/christopherkeown/anaconda3/bin/real-robots-demo", line 11, in <module>
    sys.exit(demo())
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/real_robots/cli.py", line 59, in demo
    run_episode(env, pi)
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/real_robots/cli.py", line 28, in run_episode
    observation = env.reset()
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/real_robots/envs/env.py", line 164, in reset
    return self.get_observation()
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/real_robots/envs/env.py", line 210, in get_observation
    retina = self.get_retina()
  File "/Users/christopherkeown/anaconda3/lib/python3.6/site-packages/real_robots/envs/env.py", line 193, in get_retina
    self.robot.object_bodies["table"]
AttributeError: 'BodyPart' object has no attribute 'get_position'

**Comment by emilio-cartoni** [comment]
Dear @ckeown ,
from the error message I would guess it is a problem with the pybullet version you are using.

Are you running real-robots-demo in an Anaconda virtual environment?
If you create the virtual environment as suggested [here](https://github.com/AIcrowd/neurips_goal_real_robots_starter_kit) (using [this yml file](https://github.com/AIcrowd/neurips_goal_real_robots_starter_kit/blob/master/environment.yml)) it should work.

The suggested pybullet version is: 2.5.3
