### ISSUE TITLE
Add scripts for generating a set of random goals file

### ISSUE THREAD

**Issue by spMohanty** [AIcrowd/real_robots#5]
We should include a file which can generate an arbitrary set of goals as a goals file (Which participants could potentially use for local evaluation, etc).

@emilio-cartoni : If you can write a script, and maybe just dump it in the wifi, then I could make it available as a binary embedded in the library. Feel free to include as many configurable variables as you wish.

**Comment by emilio-cartoni** [comment]
Yes, I have the one used to generate the goals.npy.npz file :)
Do you want to keep it somewhat secret? (binary)

**Comment by emilio-cartoni** [comment]
I have sent you the script via mail.

usage: generateGoals.py [-h] seed n1 n2 n3 n4 n5 n6 n7

Generate goals for the REAL Competition.

positional arguments:
  seed        seed
  n1          # of 2D Goals with 1 moving object
  n2          # of 2D Goals with 2 moving objects
  n3          # of 2D Goals with 3 moving objects
  n4          # of 2.5D Goals with 1 moving object
  n5          # of 2.5D Goals with 2 moving objects
  n6          # of 2.5D Goals with 3 moving objects
  n7          # of 3D Goals

I have run the script a couple of times and I confirm that it reproduces the same goal if given the same seed.

**Comment by emilio-cartoni** [comment]
The current goal file was generated with an unknown seed, the rest was 50 50 50 50 50 50 50 :)

**Comment by spMohanty** [comment]
I have put up the script on this wiki [here](https://github.com/AIcrowd/real_robots/wiki/Script-for-generating-new-goal-sets) for now. 

I will have the new goal sets generated, with different seeds. 

Sooner or later someone could in principle have it merged into the library as a `cli` tool, very much like we have `real-robots-demo`.

I have modified the script to make it compatible with the new library. Though it could still use a bit of refactoring, and flake8 love.

**Comment by emilio-cartoni** [comment]
I'm on it :)

**Comment by emilio-cartoni** [comment]
Done with 7cbf68fd788034b3d5b5b06711e25e012c4ddc1a and improved with 9bcfa956895129a88199d83219f683e975e79d71.
We now have a CLI  `real-robots-generate-goals` to generate the goal files.
I have also updated the [wiki page](https://github.com/AIcrowd/real_robots/wiki/Script-for-generating-new-goal-sets).
